DROP TABLE IF EXISTS Comida;

CREATE TABLE Comida (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(50),
    calorias INT,
    receta TEXT
);

INSERT INTO Comida (nombre, calorias, receta) VALUES ('Macarrones', 300, 'Lorem fistrum jarl jarl diodenoo va usté muy cargadoo qué dise usteer torpedo. Jarl fistro diodenoo torpedo al ataquerl tiene musho peligro ese pedazo de torpedo se calle ustée no puedor jarl. Ese hombree llevame al sircoo apetecan ese pedazo de de la pradera amatomaa hasta luego Lucas ese que llega llevame al sircoo a wan sexuarl. Papaar papaar te voy a borrar el cerito a peich a peich qué dise usteer se calle ustée a gramenawer no puedor. Al ataquerl está la cosa muy malar no te digo trigo por no llamarte Rodrigor qué dise usteer torpedo.');
INSERT INTO Comida (nombre, calorias, receta) VALUES ('Bocata', 288, 'Lorem fistrum jarl jarl diodenoo va usté muy cargadoo qué dise usteer torpedo. Jarl fistro diodenoo torpedo al ataquerl tiene musho peligro ese pedazo de torpedo se calle ustée no puedor jarl. Ese hombree llevame al sircoo apetecan ese pedazo de de la pradera amatomaa hasta luego Lucas ese que llega llevame al sircoo a wan sexuarl. Papaar papaar te voy a borrar el cerito a peich a peich qué dise usteer se calle ustée a gramenawer no puedor. Al ataquerl está la cosa muy malar no te digo trigo por no llamarte Rodrigor qué dise usteer torpedo.');
INSERT INTO Comida (nombre, calorias, receta) VALUES ('Tacos', 388, 'Lorem fistrum jarl jarl diodenoo va usté muy cargadoo qué dise usteer torpedo. Jarl fistro diodenoo torpedo al ataquerl tiene musho peligro ese pedazo de torpedo se calle ustée no puedor jarl. Ese hombree llevame al sircoo apetecan ese pedazo de de la pradera amatomaa hasta luego Lucas ese que llega llevame al sircoo a wan sexuarl. Papaar papaar te voy a borrar el cerito a peich a peich qué dise usteer se calle ustée a gramenawer no puedor. Al ataquerl está la cosa muy malar no te digo trigo por no llamarte Rodrigor qué dise usteer torpedo.');
INSERT INTO Comida (nombre, calorias, receta) VALUES ('Paella', 328, 'Lorem fistrum jarl jarl diodenoo va usté muy cargadoo qué dise usteer torpedo. Jarl fistro diodenoo torpedo al ataquerl tiene musho peligro ese pedazo de torpedo se calle ustée no puedor jarl. Ese hombree llevame al sircoo apetecan ese pedazo de de la pradera amatomaa hasta luego Lucas ese que llega llevame al sircoo a wan sexuarl. Papaar papaar te voy a borrar el cerito a peich a peich qué dise usteer se calle ustée a gramenawer no puedor. Al ataquerl está la cosa muy malar no te digo trigo por no llamarte Rodrigor qué dise usteer torpedo.');
INSERT INTO Comida (nombre, calorias, receta) VALUES ('Paso', 128, 'Lorem fistrum jarl jarl diodenoo va usté muy cargadoo qué dise usteer torpedo. Jarl fistro diodenoo torpedo al ataquerl tiene musho peligro ese pedazo de torpedo se calle ustée no puedor jarl. Ese hombree llevame al sircoo apetecan ese pedazo de de la pradera amatomaa hasta luego Lucas ese que llega llevame al sircoo a wan sexuarl. Papaar papaar te voy a borrar el cerito a peich a peich qué dise usteer se calle ustée a gramenawer no puedor. Al ataquerl está la cosa muy malar no te digo trigo por no llamarte Rodrigor qué dise usteer torpedo.');
INSERT INTO Comida (nombre, calorias, receta) VALUES ('Pisto', 228, 'Lorem fistrum jarl jarl diodenoo va usté muy cargadoo qué dise usteer torpedo. Jarl fistro diodenoo torpedo al ataquerl tiene musho peligro ese pedazo de torpedo se calle ustée no puedor jarl. Ese hombree llevame al sircoo apetecan ese pedazo de de la pradera amatomaa hasta luego Lucas ese que llega llevame al sircoo a wan sexuarl. Papaar papaar te voy a borrar el cerito a peich a peich qué dise usteer se calle ustée a gramenawer no puedor. Al ataquerl está la cosa muy malar no te digo trigo por no llamarte Rodrigor qué dise usteer torpedo.');
INSERT INTO Comida (nombre, calorias, receta) VALUES ('Tortilla con cebolla', 218, 'Lorem fistrum jarl jarl diodenoo va usté muy cargadoo qué dise usteer torpedo. Jarl fistro diodenoo torpedo al ataquerl tiene musho peligro ese pedazo de torpedo se calle ustée no puedor jarl. Ese hombree llevame al sircoo apetecan ese pedazo de de la pradera amatomaa hasta luego Lucas ese que llega llevame al sircoo a wan sexuarl. Papaar papaar te voy a borrar el cerito a peich a peich qué dise usteer se calle ustée a gramenawer no puedor. Al ataquerl está la cosa muy malar no te digo trigo por no llamarte Rodrigor qué dise usteer torpedo.');
INSERT INTO Comida (nombre, calorias, receta) VALUES ('Espinacas con jamón', 118, 'Lorem fistrum jarl jarl diodenoo va usté muy cargadoo qué dise usteer torpedo. Jarl fistro diodenoo torpedo al ataquerl tiene musho peligro ese pedazo de torpedo se calle ustée no puedor jarl. Ese hombree llevame al sircoo apetecan ese pedazo de de la pradera amatomaa hasta luego Lucas ese que llega llevame al sircoo a wan sexuarl. Papaar papaar te voy a borrar el cerito a peich a peich qué dise usteer se calle ustée a gramenawer no puedor. Al ataquerl está la cosa muy malar no te digo trigo por no llamarte Rodrigor qué dise usteer torpedo.');
INSERT INTO Comida (nombre, calorias, receta) VALUES ('Arroz a la cubana', 298, 'Lorem fistrum jarl jarl diodenoo va usté muy cargadoo qué dise usteer torpedo. Jarl fistro diodenoo torpedo al ataquerl tiene musho peligro ese pedazo de torpedo se calle ustée no puedor jarl. Ese hombree llevame al sircoo apetecan ese pedazo de de la pradera amatomaa hasta luego Lucas ese que llega llevame al sircoo a wan sexuarl. Papaar papaar te voy a borrar el cerito a peich a peich qué dise usteer se calle ustée a gramenawer no puedor. Al ataquerl está la cosa muy malar no te digo trigo por no llamarte Rodrigor qué dise usteer torpedo.');