CREATE TABLE "gente" (
"Nombre" TEXT,
  "Slug" TEXT,
  "Trabajo" TEXT,
  "Desc" TEXT
)
INSERT INTO gente (Nombre, Slug, Trabajo, Desc) VALUES ('Azahar Calderon Barroso', 'azahar-calderon-barroso', 'Piloto de aviación', 'Dicta nemo nam quod quidem laboriosam quos.')
INSERT INTO gente (Nombre, Slug, Trabajo, Desc) VALUES ('Eric Saldaña Vila', 'eric-saldana-vila', 'Operario en cemento armado y enfoscador', 'Aut nostrum esse quod nobis iusto. Eligendi nisi eaque mollitia nulla aliquid earum sit.')
INSERT INTO gente (Nombre, Slug, Trabajo, Desc) VALUES ('Raquel Camps Rico', 'raquel-camps-rico', 'Operario de la elaboración de productos lácteos', 'Ducimus veritatis sunt minima iste voluptatibus. Officiis consequuntur rem magni.')
INSERT INTO gente (Nombre, Slug, Trabajo, Desc) VALUES ('Rosalinda de Cortina', 'rosalinda-de-cortina', 'Técnico en asistencia al usuario de tecnología de la información y las comunicaciones', 'Nesciunt rerum similique facilis.')
INSERT INTO gente (Nombre, Slug, Trabajo, Desc) VALUES ('Adelina Sancho-Verdú', 'adelina-sancho-verdu', 'Director de servicios de cuidados infantiles', 'Nobis qui ex neque.')
INSERT INTO gente (Nombre, Slug, Trabajo, Desc) VALUES ('Valentina Ibarra Rovira', 'valentina-ibarra-rovira', 'Practicante y asistente médico', 'Molestiae perferendis ex ipsam omnis quasi at. Maxime culpa minus expedita cum fuga accusantium.')
INSERT INTO gente (Nombre, Slug, Trabajo, Desc) VALUES ('Abril Plaza-Monreal', 'abril-plaza-monreal', 'Conserje', 'Tempore modi ipsa iusto excepturi similique.')
INSERT INTO gente (Nombre, Slug, Trabajo, Desc) VALUES ('Florencio Sureda-Goicoechea', 'florencio-sureda-goicoechea', 'Gerente de hoteles o restaurantes', 'Porro maxime velit pariatur culpa magnam. Quis doloribus vero autem.')
INSERT INTO gente (Nombre, Slug, Trabajo, Desc) VALUES ('Estrella de Piñeiro', 'estrella-de-pineiro', 'Mecánico y reparador de vehículos de motor', 'Molestias ratione sint maiores ut numquam minus. Distinctio magni hic corrupti aut pariatur mollitia.')
INSERT INTO gente (Nombre, Slug, Trabajo, Desc) VALUES ('Román Casado Elorza', 'roman-casado-elorza', 'Director de investigación y desarrollo', 'Corporis fugit eaque facere aut. Beatae quae quod distinctio harum eligendi.')
INSERT INTO gente (Nombre, Slug, Trabajo, Desc) VALUES ('Salvador Villalba Ibáñez', 'salvador-villalba-ibanez', 'Costurero', 'At dolore fuga illum magni labore iure. Omnis dolores doloremque vel ab cum.')
INSERT INTO gente (Nombre, Slug, Trabajo, Desc) VALUES ('Maximiliano Garrido Arnau', 'maximiliano-garrido-arnau', 'Receptor de apuestas', 'Error enim optio cupiditate labore et non. Beatae odio nesciunt soluta cupiditate velit.')
INSERT INTO gente (Nombre, Slug, Trabajo, Desc) VALUES ('Carina de Gálvez', 'carina-de-galvez', 'Apicultor', 'Nesciunt aliquid odio quae laborum aliquid minima quisquam.')
INSERT INTO gente (Nombre, Slug, Trabajo, Desc) VALUES ('Darío Cerdán Vila', 'dario-cerdan-vila', 'Miembro de las fuerzas armadas', 'Repellat distinctio illum nesciunt earum est.')
INSERT INTO gente (Nombre, Slug, Trabajo, Desc) VALUES ('Rolando Acosta-Mayo', 'rolando-acosta-mayo', 'Mandader', 'Cumque provident dolore totam nesciunt.')
INSERT INTO gente (Nombre, Slug, Trabajo, Desc) VALUES ('Maximino Espinosa Calderon', 'maximino-espinosa-calderon', 'Inspector medioambiental y afines', 'Adipisci quisquam voluptates a necessitatibus.')
INSERT INTO gente (Nombre, Slug, Trabajo, Desc) VALUES ('Consuela de Perea', 'consuela-de-perea', 'Barnizador', 'Praesentium optio reiciendis rem vel. Assumenda laudantium accusamus repellat.')
INSERT INTO gente (Nombre, Slug, Trabajo, Desc) VALUES ('León Vallejo Ballester', 'leon-vallejo-ballester', 'Agente de administración tributaria', 'Doloribus delectus ad totam. Iusto aperiam officiis reiciendis facilis.')
INSERT INTO gente (Nombre, Slug, Trabajo, Desc) VALUES ('Glauco Oller Hervás', 'glauco-oller-hervas', 'Bombero', 'Sequi reprehenderit at distinctio.')
INSERT INTO gente (Nombre, Slug, Trabajo, Desc) VALUES ('Rodolfo Carreras Sotelo', 'rodolfo-carreras-sotelo', 'Conductor de automóviles', 'Repudiandae aliquam tempora debitis. Ullam magni nobis asperiores.')
INSERT INTO gente (Nombre, Slug, Trabajo, Desc) VALUES ('Paz Mendoza Tena', 'paz-mendoza-tena', 'Avicultor', 'Alias debitis error id.')
INSERT INTO gente (Nombre, Slug, Trabajo, Desc) VALUES ('Isidoro Montes-Montenegro', 'isidoro-montes-montenegro', 'Mecánico y reparador en electrónica', 'Ullam amet quibusdam.')
INSERT INTO gente (Nombre, Slug, Trabajo, Desc) VALUES ('Toño Raya Heras', 'tono-raya-heras', 'Pescador, cazador, tramperos y recolector de subsistencia', 'Quisquam incidunt sit cupiditate laudantium saepe.')
INSERT INTO gente (Nombre, Slug, Trabajo, Desc) VALUES ('Fabio Dávila Río', 'fabio-davila-rio', 'Vendedor de comidas al mostrador', 'Quo nisi sit. Atque provident asperiores.')
INSERT INTO gente (Nombre, Slug, Trabajo, Desc) VALUES ('Renato Vila Valverde', 'renato-vila-valverde', 'Pescador, cazador, tramperos y recolector de subsistencia', 'Possimus saepe deserunt rem sed commodi quam. Esse fugiat veritatis pariatur.')
INSERT INTO gente (Nombre, Slug, Trabajo, Desc) VALUES ('Águeda Tomasa Mesa Novoa', 'agueda-tomasa-mesa-novoa', 'Maestro preescolar', 'Repellat repudiandae possimus necessitatibus. Doloribus placeat fugiat cupiditate facere.')
INSERT INTO gente (Nombre, Slug, Trabajo, Desc) VALUES ('Fortunata Heredia Ariño', 'fortunata-heredia-arino', 'Chef', 'Ut deleniti blanditiis explicabo eum.')
INSERT INTO gente (Nombre, Slug, Trabajo, Desc) VALUES ('Rosalía Miró Guitart', 'rosalia-miro-guitart', 'Gorjadore', 'Beatae dolorum magnam voluptas dolorem expedita.')
INSERT INTO gente (Nombre, Slug, Trabajo, Desc) VALUES ('Eric Ariño Yuste', 'eric-arino-yuste', 'Inspector de la salud laboral', 'Ex molestiae perferendis reiciendis dolore.')
INSERT INTO gente (Nombre, Slug, Trabajo, Desc) VALUES ('Teodoro Font Gibert', 'teodoro-font-gibert', 'Marinero de cubierta', 'Voluptas commodi minus delectus velit.')
